# This file was generated by GoReleaser. DO NOT EDIT.
class Keys.Pub < Formula
  desc ""
  homepage "https://keys.pub"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/keys-pub/keysd/releases/download/v0.0.2/keys_0.0.2_darwin_x86_64.tar.gz"
    sha256 "dfd7b388c400b5c2d39a24a94f043bb975b285175a16330562a58f1de118f3a8"
  elsif OS.linux?
  end

  def install
    bin.install "keys"
    bin.install "keysd"
  end
end
