# This file was generated by GoReleaser. DO NOT EDIT.
class Keys.Pub < Formula
  desc ""
  homepage "https://keys.pub"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/keys-pub/keysd/releases/download/v0.0.2/keys_0.0.2_darwin_x86_64.tar.gz"
    sha256 "3e4962728985bdad7fd41a340267cec8f8c859a1929b4454d62b919de8457884"
  elsif OS.linux?
  end

  def install
    bin.install "keys"
    bin.install "keysd"
  end
end
