# This file was generated by GoReleaser. DO NOT EDIT.
class Keys < Formula
  desc ""
  homepage "https://keys.pub"
  version "0.0.35"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/keys-pub/keysd/releases/download/v0.0.35/keys_0.0.35_darwin_x86_64.tar.gz"
    sha256 "85cc7f9fe193339686f33c38ec34a1fb0b8843d708dde8b41a9dc8db81582dbd"
  elsif OS.linux?
  end

  def install
    bin.install "keys"
    bin.install "keysd"
  end
end
